env:
  es6: true
  node: true
extends:
  - airbnb-base
  - eslint:recommended
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
rules:
  linebreak-style: 0
  quotes:
    - 2
    - single
    - allowTemplateLiterals: true
  no-mixed-spaces-and-tabs: 2
  prettier/prettier: 2
